//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 211506372
//  @ File Name : StaticData.h
//  @ Date : 2017/12/05
//  @ Author : lichengbin
//
//


#if !defined(_STATICDATA_H)
#define _STATICDATA_H

#include "cocos2d.h"
#include<string>
using namespace std;
USING_NS_CC;

#define STATIC_DATA_FILENAME "static_data.plist"
#define CC_SAFE_RELEASE_NULL(p) do { if(p) { (p)->release(); (p) = 0; } } while(0)
#define STATIC_DATA_STRING(key) StaticData::sharedStaticData()->stringValueFromKey(key)



class StaticData:public CCObject {
public:
	static StaticData* sharedStaticData();
	static void purge();
	int intValueForKey(const std::string &key);
	const char* stringValueFromKey(const std::string &key);
	float floatValueFromKey(const std::string &key);
	bool booleanFromKey(const std::string &key);
	cocos2d::CCPoint pointFromKey(const std::string &key);
	cocos2d::CCRect rectFromKey(const std::string &key);
	cocos2d::CCSize sizeFormKey(const std::string &key);
protected:
	cocos2d::CCDictionary* _dictionary;
	std::string _staticFileName;
	bool init();
private:
	~StaticData();
	StaticData();
};

#endif  //_STATICDATA_H
